
# build and package the UmbPack
name: Build and Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    # Build Steps
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Setup .net core 
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    # get other package dependencies
    - name: Install Dependencies
      run: dotnet restore src/UmbPack.sln
      
    # build the project 
    - name: Build
      run: dotnet build src/UmbPack.sln --configuration Release --no-restore
    
    # TODO: Package it up and publish somewhere? 
